default:
	hugo

export-docs:
	git update-ref refs/heads/master origin/master '' 2>/dev/null || true
	GIT_INDEX_FILE=gitindex.tmp; export GIT_INDEX_FILE; \
	rm -f $${GIT_INDEX_FILE} && \
	git add -f public/* && \
	git update-ref refs/heads/master \
		$$(echo "Autogenerated html pages for $$(git describe)" \
		| git commit-tree $$(git write-tree --prefix=public) \
		-p refs/heads/master)

push-docs: export-docs
	    git push origin master

gh-pages: export-docs
	    git push origin +master:master # this was pushing to gh-pages
